/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NetworkRouteRouteImport } from './routes/network/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NetworkWatchRouteImport } from './routes/network/watch'
import { Route as NetworkNetworkIdRouteImport } from './routes/network/$networkId'
import { Route as ApiSchemaRouteImport } from './routes/api/schema'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiNetworkRouteImport } from './routes/api/network'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as ApiSchemaValidateRouteImport } from './routes/api/schema/validate'
import { Route as ApiSchemaPropertiesRouteImport } from './routes/api/schema/properties'
import { Route as ApiSchemaNetworkRouteImport } from './routes/api/schema/network'
import { Route as ApiSchemaVersionRouteImport } from './routes/api/schema/$version'
import { Route as ApiNetworkNodesRouteImport } from './routes/api/network/nodes'
import { Route as ApiNetworkEdgesRouteImport } from './routes/api/network/edges'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as ApiSchemaNetworkValidateRouteImport } from './routes/api/schema/network/validate'
import { Route as ApiSchemaNetworkPropertiesRouteImport } from './routes/api/schema/network/properties'

const NetworkRouteRoute = NetworkRouteRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkWatchRoute = NetworkWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const NetworkNetworkIdRoute = NetworkNetworkIdRouteImport.update({
  id: '/$networkId',
  path: '/$networkId',
  getParentRoute: () => NetworkRouteRoute,
} as any)
const ApiSchemaRoute = ApiSchemaRouteImport.update({
  id: '/api/schema',
  path: '/api/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNetworkRoute = ApiNetworkRouteImport.update({
  id: '/api/network',
  path: '/api/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaValidateRoute = ApiSchemaValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => ApiSchemaRoute,
} as any)
const ApiSchemaPropertiesRoute = ApiSchemaPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => ApiSchemaRoute,
} as any)
const ApiSchemaNetworkRoute = ApiSchemaNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => ApiSchemaRoute,
} as any)
const ApiSchemaVersionRoute = ApiSchemaVersionRouteImport.update({
  id: '/$version',
  path: '/$version',
  getParentRoute: () => ApiSchemaRoute,
} as any)
const ApiNetworkNodesRoute = ApiNetworkNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => ApiNetworkRoute,
} as any)
const ApiNetworkEdgesRoute = ApiNetworkEdgesRouteImport.update({
  id: '/edges',
  path: '/edges',
  getParentRoute: () => ApiNetworkRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSchemaNetworkValidateRoute =
  ApiSchemaNetworkValidateRouteImport.update({
    id: '/validate',
    path: '/validate',
    getParentRoute: () => ApiSchemaNetworkRoute,
  } as any)
const ApiSchemaNetworkPropertiesRoute =
  ApiSchemaNetworkPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => ApiSchemaNetworkRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/network': typeof NetworkRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/network': typeof ApiNetworkRouteWithChildren
  '/api/query': typeof ApiQueryRoute
  '/api/schema': typeof ApiSchemaRouteWithChildren
  '/network/$networkId': typeof NetworkNetworkIdRoute
  '/network/watch': typeof NetworkWatchRoute
  '/api/network/edges': typeof ApiNetworkEdgesRoute
  '/api/network/nodes': typeof ApiNetworkNodesRoute
  '/api/schema/$version': typeof ApiSchemaVersionRoute
  '/api/schema/network': typeof ApiSchemaNetworkRouteWithChildren
  '/api/schema/properties': typeof ApiSchemaPropertiesRoute
  '/api/schema/validate': typeof ApiSchemaValidateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/schema/network/properties': typeof ApiSchemaNetworkPropertiesRoute
  '/api/schema/network/validate': typeof ApiSchemaNetworkValidateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/network': typeof NetworkRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/network': typeof ApiNetworkRouteWithChildren
  '/api/query': typeof ApiQueryRoute
  '/api/schema': typeof ApiSchemaRouteWithChildren
  '/network/$networkId': typeof NetworkNetworkIdRoute
  '/network/watch': typeof NetworkWatchRoute
  '/api/network/edges': typeof ApiNetworkEdgesRoute
  '/api/network/nodes': typeof ApiNetworkNodesRoute
  '/api/schema/$version': typeof ApiSchemaVersionRoute
  '/api/schema/network': typeof ApiSchemaNetworkRouteWithChildren
  '/api/schema/properties': typeof ApiSchemaPropertiesRoute
  '/api/schema/validate': typeof ApiSchemaValidateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/schema/network/properties': typeof ApiSchemaNetworkPropertiesRoute
  '/api/schema/network/validate': typeof ApiSchemaNetworkValidateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/network': typeof NetworkRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/network': typeof ApiNetworkRouteWithChildren
  '/api/query': typeof ApiQueryRoute
  '/api/schema': typeof ApiSchemaRouteWithChildren
  '/network/$networkId': typeof NetworkNetworkIdRoute
  '/network/watch': typeof NetworkWatchRoute
  '/api/network/edges': typeof ApiNetworkEdgesRoute
  '/api/network/nodes': typeof ApiNetworkNodesRoute
  '/api/schema/$version': typeof ApiSchemaVersionRoute
  '/api/schema/network': typeof ApiSchemaNetworkRouteWithChildren
  '/api/schema/properties': typeof ApiSchemaPropertiesRoute
  '/api/schema/validate': typeof ApiSchemaValidateRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/schema/network/properties': typeof ApiSchemaNetworkPropertiesRoute
  '/api/schema/network/validate': typeof ApiSchemaNetworkValidateRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/network'
    | '/api/health'
    | '/api/network'
    | '/api/query'
    | '/api/schema'
    | '/network/$networkId'
    | '/network/watch'
    | '/api/network/edges'
    | '/api/network/nodes'
    | '/api/schema/$version'
    | '/api/schema/network'
    | '/api/schema/properties'
    | '/api/schema/validate'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/schema/network/properties'
    | '/api/schema/network/validate'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/network'
    | '/api/health'
    | '/api/network'
    | '/api/query'
    | '/api/schema'
    | '/network/$networkId'
    | '/network/watch'
    | '/api/network/edges'
    | '/api/network/nodes'
    | '/api/schema/$version'
    | '/api/schema/network'
    | '/api/schema/properties'
    | '/api/schema/validate'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/schema/network/properties'
    | '/api/schema/network/validate'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/network'
    | '/api/health'
    | '/api/network'
    | '/api/query'
    | '/api/schema'
    | '/network/$networkId'
    | '/network/watch'
    | '/api/network/edges'
    | '/api/network/nodes'
    | '/api/schema/$version'
    | '/api/schema/network'
    | '/api/schema/properties'
    | '/api/schema/validate'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/schema/network/properties'
    | '/api/schema/network/validate'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkRouteRoute: typeof NetworkRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNetworkRoute: typeof ApiNetworkRouteWithChildren
  ApiQueryRoute: typeof ApiQueryRoute
  ApiSchemaRoute: typeof ApiSchemaRouteWithChildren
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/watch': {
      id: '/network/watch'
      path: '/watch'
      fullPath: '/network/watch'
      preLoaderRoute: typeof NetworkWatchRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/network/$networkId': {
      id: '/network/$networkId'
      path: '/$networkId'
      fullPath: '/network/$networkId'
      preLoaderRoute: typeof NetworkNetworkIdRouteImport
      parentRoute: typeof NetworkRouteRoute
    }
    '/api/schema': {
      id: '/api/schema'
      path: '/api/schema'
      fullPath: '/api/schema'
      preLoaderRoute: typeof ApiSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/network': {
      id: '/api/network'
      path: '/api/network'
      fullPath: '/api/network'
      preLoaderRoute: typeof ApiNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema/validate': {
      id: '/api/schema/validate'
      path: '/validate'
      fullPath: '/api/schema/validate'
      preLoaderRoute: typeof ApiSchemaValidateRouteImport
      parentRoute: typeof ApiSchemaRoute
    }
    '/api/schema/properties': {
      id: '/api/schema/properties'
      path: '/properties'
      fullPath: '/api/schema/properties'
      preLoaderRoute: typeof ApiSchemaPropertiesRouteImport
      parentRoute: typeof ApiSchemaRoute
    }
    '/api/schema/network': {
      id: '/api/schema/network'
      path: '/network'
      fullPath: '/api/schema/network'
      preLoaderRoute: typeof ApiSchemaNetworkRouteImport
      parentRoute: typeof ApiSchemaRoute
    }
    '/api/schema/$version': {
      id: '/api/schema/$version'
      path: '/$version'
      fullPath: '/api/schema/$version'
      preLoaderRoute: typeof ApiSchemaVersionRouteImport
      parentRoute: typeof ApiSchemaRoute
    }
    '/api/network/nodes': {
      id: '/api/network/nodes'
      path: '/nodes'
      fullPath: '/api/network/nodes'
      preLoaderRoute: typeof ApiNetworkNodesRouteImport
      parentRoute: typeof ApiNetworkRoute
    }
    '/api/network/edges': {
      id: '/api/network/edges'
      path: '/edges'
      fullPath: '/api/network/edges'
      preLoaderRoute: typeof ApiNetworkEdgesRouteImport
      parentRoute: typeof ApiNetworkRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/schema/network/validate': {
      id: '/api/schema/network/validate'
      path: '/validate'
      fullPath: '/api/schema/network/validate'
      preLoaderRoute: typeof ApiSchemaNetworkValidateRouteImport
      parentRoute: typeof ApiSchemaNetworkRoute
    }
    '/api/schema/network/properties': {
      id: '/api/schema/network/properties'
      path: '/properties'
      fullPath: '/api/schema/network/properties'
      preLoaderRoute: typeof ApiSchemaNetworkPropertiesRouteImport
      parentRoute: typeof ApiSchemaNetworkRoute
    }
  }
}

interface NetworkRouteRouteChildren {
  NetworkNetworkIdRoute: typeof NetworkNetworkIdRoute
  NetworkWatchRoute: typeof NetworkWatchRoute
}

const NetworkRouteRouteChildren: NetworkRouteRouteChildren = {
  NetworkNetworkIdRoute: NetworkNetworkIdRoute,
  NetworkWatchRoute: NetworkWatchRoute,
}

const NetworkRouteRouteWithChildren = NetworkRouteRoute._addFileChildren(
  NetworkRouteRouteChildren,
)

interface ApiNetworkRouteChildren {
  ApiNetworkEdgesRoute: typeof ApiNetworkEdgesRoute
  ApiNetworkNodesRoute: typeof ApiNetworkNodesRoute
}

const ApiNetworkRouteChildren: ApiNetworkRouteChildren = {
  ApiNetworkEdgesRoute: ApiNetworkEdgesRoute,
  ApiNetworkNodesRoute: ApiNetworkNodesRoute,
}

const ApiNetworkRouteWithChildren = ApiNetworkRoute._addFileChildren(
  ApiNetworkRouteChildren,
)

interface ApiSchemaNetworkRouteChildren {
  ApiSchemaNetworkPropertiesRoute: typeof ApiSchemaNetworkPropertiesRoute
  ApiSchemaNetworkValidateRoute: typeof ApiSchemaNetworkValidateRoute
}

const ApiSchemaNetworkRouteChildren: ApiSchemaNetworkRouteChildren = {
  ApiSchemaNetworkPropertiesRoute: ApiSchemaNetworkPropertiesRoute,
  ApiSchemaNetworkValidateRoute: ApiSchemaNetworkValidateRoute,
}

const ApiSchemaNetworkRouteWithChildren =
  ApiSchemaNetworkRoute._addFileChildren(ApiSchemaNetworkRouteChildren)

interface ApiSchemaRouteChildren {
  ApiSchemaVersionRoute: typeof ApiSchemaVersionRoute
  ApiSchemaNetworkRoute: typeof ApiSchemaNetworkRouteWithChildren
  ApiSchemaPropertiesRoute: typeof ApiSchemaPropertiesRoute
  ApiSchemaValidateRoute: typeof ApiSchemaValidateRoute
}

const ApiSchemaRouteChildren: ApiSchemaRouteChildren = {
  ApiSchemaVersionRoute: ApiSchemaVersionRoute,
  ApiSchemaNetworkRoute: ApiSchemaNetworkRouteWithChildren,
  ApiSchemaPropertiesRoute: ApiSchemaPropertiesRoute,
  ApiSchemaValidateRoute: ApiSchemaValidateRoute,
}

const ApiSchemaRouteWithChildren = ApiSchemaRoute._addFileChildren(
  ApiSchemaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkRouteRoute: NetworkRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiNetworkRoute: ApiNetworkRouteWithChildren,
  ApiQueryRoute: ApiQueryRoute,
  ApiSchemaRoute: ApiSchemaRouteWithChildren,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
